### ISSUE TITLE
CSV rendering doesn't work after dependencies upgrade

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana-image-renderer#371]
**What happened**:
Seems like CSV rendering got broken after https://github.com/grafana/grafana-image-renderer/pull/369. The error trace: 
```
error:  Request failed {"stack":"TypeError: page._client.send is not a function\n    at Browser.exportCSV (/Users/alexkhomenko/dev/go/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:375:28)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Browser.renderCSV (/Users/alexkhomenko/dev/go/src/github.com/grafana/grafana-image-renderer/build/browser/browser.js:351:20)\n    at async HttpServer.renderCSV (/Users/alexkhomenko/dev/go/src/github.com/grafana/grafana-image-renderer/build/service/http-server.js:123:28)","url":"/render/csv?domain=localhost&encoding=&renderKey=r32lUpzlhGsWUm4uCdDiTyOrelgXHG6Q&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-csv%2FCvaPe9vnz%3Ffrom%3D1663908146000%26panelId%3D2%26to%3D1663929746000%26render%3D1"}
error:  127.0.0.1 - - [23/Sep/2022:10:42:28 +0000] "GET /render/csv?domain=localhost&encoding=&renderKey=r32lUpzlhGsWUm4uCdDiTyOrelgXHG6Q&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fd-csv%2FCvaPe9vnz%3Ffrom%3D1663908146000%26panelId%3D2%26to%3D1663929746000%26render%3D1 HTTP/1.1" 500 96 "-" "Grafana/9.2.0-pre"
```

It seems like an API change in Puppeteer and `page._client.send` doesn't exist anymore (doesn't help that we type `page` as `any`). 

**What you expected to happen**:

When rendering a report with CSV option on, the table data from the report's dashboards should be included in the report email. 

**How to reproduce it (as minimally and precisely as possible)**:
- Create a report with a dashboard that has at least one panel with table data
- Select PDF (or image) and CSV format options in the report's `Format` section
- Go to the `Share` section, fill in the required fields
- Press `Send test email` and send it to a valid address.
- Verify that the received email doesn't have CSV data included as a separate file.

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version:
- Grafana version:
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on:
- User OS & Browser:
- Others:
